config/routes.rb
EmployeeSearch::Application.routes.draw do

  mount Mercury::Engine => '/'

  resources :galleries
  resources :employees
  resources :photos do
    resources :likes
  end
  resources :pages do
    resources :likes
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root :to => 'welcome#index'
  resources :welcome, :only => [] do
    member { put :mercury_update }
  end

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :photos
  validates_presence_of :name, :description
end

app/controllers/galleries_controller.rb
# -*- coding: utf-8 -*-
class GalleriesController < ApplicationController
  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = GalleryDecorator.decorate(Gallery.find(:all, :include => {:photos => :likes}))

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = GalleryDecorator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @galleries = GalleryDecorator.decorate(Gallery.find(:all, :include => :photos))
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to galleries_path, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "index" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        # format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
    render :action => "show"
        format.json { head :no_content }
      else
        # format.html { render action: "edit" }
        format.html { render action: "show" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<%= simple_form_for @gallery ? @gallery : Gallery.new, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-inputs">
    <%= f.input :name, :label => "タイトル" %>
    <%= f.input :description, :label => "説明" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "追加する", :class => 'btn btn-primary' %>
    <%= f.button :button, "やめる", :class => 'btn', :type => 'button', :id => 'upload_cancel' %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<%- model_class = @gallery.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/galleries/index.html.erb
<div class="row">
  <div class="page-header">
    <h1>アルバム ギャラリー
      <small>アルバム名をclickすると詳細が見れます。 chrome または firefox 推奨
      </h1>
    </div>
    <div class="accordion-group" style="margin-bottom: 5px">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" href="#collapseOne">アルバムを追加する</a>
      </div>
      <div id="collapseOne" class="accordion-body collapse" style="height: 0px; ">
        <div class="accordion-inner">
          <%= render :partial => 'form' %>
        </div>
      </div>
    </div>
    <table id="album" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th style="width:150px">人気数(TOTAL)</th>
          <th>最近アップした写真</th>
          <th>アルバム名</th>
          <th>説明</th>
        </tr>
      </thead>
      <tbody>
        <% @galleries.each do |gallery| %>
          <tr>
            <td>
              <div class="btn-toolbar">
                <div class="btn-group">
                  <button class="btn btn-info disabled"><i class='icon-thumbs-up icon-white'></i>いいね！</button>
                  <button class="btn btn-info disabled"><%= gallery.photos.inject(0){|v, r| v += r.likes.length} %></button>
                </div>
              </div>
            </td>
            <td><%= gallery.small_thumbnails %></td>
            <td><%= link_to gallery.name, gallery_path(gallery) %></td>
            <td><%= gallery.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/galleries/new.html.erb
<%- model_class = @gallery.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/galleries/show.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>
        <%= @gallery.name %>
        <small><%= @gallery.description %></small>
      </h1>
    </div>
    <div class="accordion-group" style="margin-bottom: 5px">
      <button class="btn btn-primary" data-toggle="collapse" href="#collapseOne">
        <i class="icon-upload icon-white"></i>
        写真を追加する
      </button>
      <div id="collapseOne" class="accordion-body collapse" style="height: 0px; ">
        <div class="accordion-inner">
          <%= simple_form_for(@photo ? @photo : Photo.new, :url => photos_path, :html => { :class => 'form-horizontal' }) do |f| %>
            <div class="form-inputs">
              <%= f.input :name, :label => "タイトル" %>
              <%= f.input :description, :label => "説明", :input_html => {:style => 'width: 490px'} %>
              <%= f.input :photo, :class => 'input-file', :label => '写真' %>
              <%= f.hidden_field :gallery_id, :value => @gallery.id %>
            </div>

            <div class="form-actions">
              <%= f.button :submit, "追加する", :class => 'btn btn-primary' %>
              <%= f.button :button, "やめる", :class => 'btn', :type => 'button', :id => 'upload_cancel' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div id="photos_list" class="thumbnails">
      <% @gallery.photos.each do |photo| %>
        <div class="span3" style="margin-bottom:15px">
          <div class="thumbnail">
            <%= image_tag photo.photo.photo_url(:thumb), id: :thumbnail %>
            <div class="caption">
              <h5><%= best_in_place photo, :name, :display_as => :dsp_name %></h5>
              <p><%= best_in_place photo, :description, :display_as => :dsp_description %></p>
              <p>
                <span id="<%= "like_#{photo.id}" %>"><%= photo.like_button %></span>
                <span id="<%= "badge_#{photo.id}" %>"><%= photo.like_badge %></span>
                <%= link_to photo, confirm: '本当に削除しますか？', method: :delete, :class => 'btn btn-danger btn-mini pull-right' do %>
                  <i class="icon-trash icon-white"></i>
                <% end %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/galleries/show.js.erb
$("<%= "#badge_#{@likable.id}" %>").html("<%= j(@likable.like_badge) %>")
$("<%= "#like_#{@likable.id}" %>").html("<%= j(@likable.like_button) %>")