config/routes.rb
EmployeeSearch::Application.routes.draw do

  mount Mercury::Engine => '/'

  resources :galleries
  resources :employees
  resources :photos do
    resources :likes
  end
  resources :pages do
    resources :likes
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root :to => 'welcome#index'
  resources :welcome, :only => [] do
    member { put :mercury_update }
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="overflow:auto;">
  <head>
    <title>uelbook</title>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container" style="height:40px">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>">UELBOOK</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "社内ホームページ" %></li>
              <li class="<%= active_employees?(request) %>"><%= link_to "社員検索", employees_path %></li>
              <li class="<%= active_album?(request) %>"><%= link_to "写真館", galleries_path %></li>
              <li><%= link_to "Kunitter" %></li>
            </ul>
          </div>
          <ul class="nav pull-right">
            <% if current_user %>
              <li style="width:40px; height:38px"><%= image_tag current_user.image, :size => "38x40" %></li>
              <li class="dropdown" id="menu1">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
                  <strong><%= current_user.name %></strong>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'ログアウト', destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
            <% else %>
              <li>
                <%= link_to image_tag("/assets/twitter.png", :size => "28x28"),
                  user_omniauth_authorize_path(:twitter), :rel => "tooltip", "data-original-title" => "sign in through twitter" %>
              </li>
              <li>
                <%= link_to image_tag("/assets/facebook.png", :size => "28x28"),
                  user_omniauth_authorize_path(:facebook), :rel => "tooltip", "data-original-title" => "sign in through facebook" %>
              </li>
            <% end %>
          </ul>
          <%= form_tag employees_path, :method => :get, :class => "navbar-search" do %>
            <div class="icon-search icon-white"></div>
            <%= text_field_tag :search, params[:search], :class => "search-query", :placeholder => "社員検索" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="container">
      <%= create_alert_message("alert", "success", notice, true) %>
      <%= create_alert_message("alert", "alert", alert, true) %>
      <%= yield %>
    </div>
    <div id="sign_in" class="sign-modal hide fade" style="">
      <div class="modal-body">
      </div>
    </div>
  </body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag 'jquery-1.7', 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  'form', // 'form', or 'json' (default json)
        saveMethod: 'PUT', // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>

</html>